name: Lint

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'website/**'
  pull_request:
    paths-ignore:
      - 'website/**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.6.0'
    - name: Install dependencies
      run: npm ci
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx --ignore-pattern 'widgets/**/*.js'